# HTTPS virtual host
<VirtualHost *:443>
    ServerName email.ops345.lovepreetsingh.site
    DocumentRoot /var/www/html/roundcube

    SSLEngine on
    SSLCertificateFile /etc/pki/tls/certs/email.ops345.lovepreetsingh.site.cert.pem
    SSLCertificateKeyFile /etc/pki/tls/private/email.ops345.lovepreetsingh.site.key.pem

    <Directory /var/www/html/roundcube>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
